TrajectoryPlannerROS:
  max_vel_x: 1.0
  min_vel_x: -0.5
  max_vel_theta: 2.0
  min_vel_theta: -2.0
 
  min_in_place_rotational_vel: 1.4

  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 3.2

  # fifth_robot is not a holonomic robot
  holonomic_robot: true

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1

  sim_time: 4.0
  controller_frequency: 5.0
  # Length of view when rotate
  heading_lookahead: 15.0
  # Use method of Dynamic Window Approach
  heading_scoring: false
  heading_scoring_timestamp: 0.5
  dwa: true

  # Show cost map
  publish_cost_grid_pc: true
  global_frame_id: floor

  pdist_scale: 1.2
  gdist_scale: 0.8
  occdist_scale: 0.01

  meter_scoring: true
