controller_frequency: 10.0
controller_patience: 10.0

planner_patience: 5.0
planner_frequency: 4.0

recovery_behavior_enabled: true
clearing_rotation_allowed: true
shutdown_costmaps: false

oscillation_timeout: 10.0
oscillation_distance: 0.2

max_planning_retries: 10
conservative_reset_dist: 6.0
