- name: start
  x: 10
  y: 10
  inportance: 1
  radius: 1.5
  drag: 5

- name: gate
  x: 10
  y: 20
  inportance: 2
  radius: 2.5
  drag: 3

- name: lope
  x: 20
  y: 20
  inportance: 3
  radius: 0.5

- name: goal
  x: 20
  y: 20
  inportance: 4
  radius: 0.5
