obstacle_range: 12.0
raytrace_range: 15.0
# footprint for KIT-C5 new model
footprint: [[0.1, 0.4], [0.1, -0.4], [-0.4, -0.4], [-0.4, 0.4]]
inflation_radius: 0.5
cost_scaling_factor: 7.0

rigin_z: 0.0
z_resolution: 0.2
z_voxels: 0.2
publish_voxel_map: false
max_obstacle_height: 0.4
min_obstacle_height: 0.05

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: front_urg_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

# observation_sources: velodyne_sensor
# velodyne_sensor: {sensor_frame: velodyne_link, data_type: PointCloud2, topic: points2, marking: true, clearing: true}

