obstacle_range: 12.0
raytrace_range: 15.0
# footprint for KIT-C5 new model
footprint: [[0.07, -0.30], [0.07, 0.30], [-0.43, 0.30], [-0.43, -0.30]]
inflation_radius: 0.5
cost_scaling_factor: 7.0

rigin_z: 0.0
z_resolution: 0.2
z_voxels: 0.2
publish_voxel_map: false
max_obstacle_height: 0.8
min_obstacle_height: 0.1

observation_sources: velodyne_sensor
velodyne_sensor: {
  sensor_frame: velodyne_link,
  data_type: PointCloud2,
  topic: velodyne_points,
  marking: true,
  clearing: true,
  min_obstacle_height: 0.1,
  max_obstacle_height: 0.8
}

