obstacle_range: 5.0
raytrace_range: 10.0

# footprint for KIT-C5 new model
# footprint: [[0.00, -0.25], [0.00, 0.25], [-0.60, 0.25], [-0.60, -0.25]]
inflation_radius: 0.35
cost_scaling_factor: 5.0

rigin_z: 0.0
z_resolution: 0.02
z_voxels: 0.02
publish_voxel_map: false

observation_sources: velodyne_sensor
velodyne_sensor: {
  sensor_frame: velodyne_link,
  data_type: PointCloud2,
  topic: velodyne_points,
  # expected_update_rate: 1.0,
  observation_persistence: 0.0, 
  marking: true,
  clearing: true,
  min_obstacle_height: 0.2,
  max_obstacle_height: 0.8,
}

