local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 10.0
  width: 15.0
  height: 15.0
  resolution: 0.2
  # must not be changed
  static_map: false
  rolling_window: true
transform_tolerance: 1.5
