local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 8.0
  publish_frequency: 7.0
  width: 10.0
  height: 10.0
  resolution: 0.02
  meter_scoring: true
  static_map: false
  rolling_window: true
